name: build

on:
  push:
  pull_request:

jobs:
  test-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Show Python version
        shell: pwsh
        run: python --version

      - name: Compile all python files
        shell: pwsh
        run: python -m compileall -q .

      - name: Run basic command (no options)
        shell: pwsh
        run: python src/main.py data/test.csv

      - name: Stats test
        shell: pwsh
        run: python src/main.py data/test.csv --stats Pret

      - name: Filter AND test
        shell: pwsh
        run: python src/main.py data/test.csv --filter "Pret>100 AND Categorie='Electronice'"

      - name: Groupby test
        shell: pwsh
        run: python src/main.py data/test.csv --groupby Categorie --agg "avg:Pret,sum:Vanzari,count:Pret"

      - name: Correlation test
        shell: pwsh
        run: python src/main.py data/test.csv --correlation Pret Vanzari

      - name: Histogram test
        shell: pwsh
        run: python src/main.py data/test.csv --plot histogram Varsta

      - name: Clean + Export test
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path data | Out-Null
          python src/main.py data/test.csv --clean missing --fill mean --output data/clean.csv
          if (!(Test-Path "data/clean.csv")) { throw "data/clean.csv nu a fost creat" }

  docker-build:
    runs-on: windows-latest
    needs: test-windows
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Docker build (optional)
        shell: pwsh
        run: docker build -t csv-processor .
