name: publicare-dockerhub

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  push-dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Preluare repository
        uses: actions/checkout@v4

      - name: Autentificare Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build si push imagine
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/procesor-de-date-csv:latest
